apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy/alloy.yaml
  - loki/loki.yaml
  - tempo/tempo.yaml
  - prometheus/prometheus.yaml
  - grafana/grafana.yaml
  - infrastructure/infrastructure.yaml
