# EKS target for the agent demo. Scaffold, partial.
# Spot nodes and short-lived by design: applied for a session, destroyed after.

terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
  }
}

variable "region"       { default = "us-east-2" }
variable "cluster_name" { default = "axiom-aiops-demo" }

# Node group intentionally small. The agent is not the load, the boutique app is,
# and the load profile is generated by an in-cluster k6 job.
locals {
  node_group = {
    instance_types = ["t3.large"]
    capacity_type  = "SPOT"
    min_size       = 2
    max_size       = 4
    desired_size   = 2
  }

  # Attached only when serving the fine-tuned model. Not enabled in this snapshot.
  gpu_node_group = {
    instance_types = ["g5.xlarge"]
    capacity_type  = "SPOT"
    min_size       = 0
    max_size       = 1
    desired_size   = 0
  }
}

# The agent's IRSA role. Narrow on purpose: read telemetry, patch a short list of
# resource kinds in one namespace. No delete, no RBAC, no cross-namespace reach.
# If the action policy is ever bypassed, this is the boundary that still holds.
